const OPAQUE = 'rgba(17,17,17, 1)';
const TRANSPARENT = 'rgba(17,17,17, .8)';

export const EVENTS = {
  EMIT: {
    CREATE_ROOM: 'CREATE_ROOM',
    JOIN_ROOM: 'JOIN_ROOM',
    SEND_MESSAGE: 'SEND_MESSAGE',
    MARK_AS_READ: 'MARK_AS_READ',
    REACT_TO_MESSAGE: 'REACT_TO_MESSAGE',
    UNREACT_TO_MESSAGE: 'UNREACT_TO_MESSAGE',
    TYPING: 'TYPING',
    STOP_TYPING: 'STOP_TYPING',
    EDIT_MESSAGE: 'EDIT_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
  },
  ON: {
    JOINED_ROOM: 'JOINED_ROOM',
    MESSAGES: 'MESSAGES',
    USER_ONLINE: 'USER_ONLINE',
    USER_OFFLINE: 'USER_OFFLINE',
    NEW_MESSAGE: 'NEW_MESSAGE',
    NEW_CHAT_CREATED: 'NEW_CHAT_CREATED',
    MESSAGES_READ: 'MESSAGES_READ',
    MESSAGE_REACTED: 'MESSAGE_REACTED',
    MESSAGE_UNREACTED: 'MESSAGE_UNREACTED',
    USER_TYPING: 'USER_TYPING',
    USER_STOPPED_TYPING: 'USER_STOPPED_TYPING',
    MESSAGE_EDITED: 'MESSAGE_EDITED',
    MESSAGE_DELETED: 'MESSAGE_DELETED',
  },
};

export const GC_EVENTS = {
  EMIT: {
    // CREATE_ROOM: 'CREATE_ROOM',
    JOIN_ROOM: 'GC_JOIN_ROOM',
    SEND_MESSAGE: 'GC_SEND_MESSAGE',
    MARK_AS_READ: 'GC_MARK_AS_READ',
    REACT_TO_MESSAGE: 'GC_REACT_TO_MESSAGE',
    UNREACT_TO_MESSAGE: 'GC_UNREACT_TO_MESSAGE',
    TYPING: 'GC_TYPING',
    STOP_TYPING: 'GC_STOP_TYPING',
    EDIT_MESSAGE: 'GC_EDIT_MESSAGE',
    DELETE_MESSAGE: 'GC_DELETE_MESSAGE',
    GC_MAKE_ADMIN: 'GC_MAKE_ADMIN',
    GC_REMOVE_ADMIN: 'GC_REMOVE_ADMIN',
    GC_ADD_MEMBER: 'GC_ADD_MEMBER',
    GC_REMOVE_MEMBER: 'GC_REMOVE_MEMBER',
    GC_LOAD_MORE_MESSAGES: 'GC_LOAD_MORE_MESSAGES',
  },
  ON: {
    JOINED_ROOM: 'GC_JOINED_ROOM',
    MESSAGES: 'GC_MESSAGES',
    // USER_ONLINE: 'USER_ONLINE',
    // USER_OFFLINE: 'USER_OFFLINE',
    NEW_MESSAGE: 'GC_NEW_MESSAGE',
    // NEW_CHAT_CREATED: 'NEW_CHAT_CREATED',
    MESSAGES_READ: 'GC_MESSAGES_READ',
    MESSAGE_REACTED: 'GC_MESSAGE_REACTED',
    MESSAGE_UNREACTED: 'GC_MESSAGE_UNREACTED',
    USER_TYPING: 'GC_USER_TYPING',
    USER_STOPPED_TYPING: 'GC_USER_STOPPED_TYPING',
    MESSAGE_EDITED: 'GC_MESSAGE_EDITED',
    MESSAGE_DELETED: 'GC_MESSAGE_DELETED',

    GC_ADMIN_UPDATED: 'GC_ADMIN_UPDATED',
    GC_MEMBER_UPDATED: 'GC_MEMBER_UPDATED',
  },
};

const DEFAULT_EMOJIS = ['👍', '❤️', '😂', '😮', '😢', '🙏'];

export const constants = { OPAQUE, TRANSPARENT, DEFAULT_EMOJIS };
