const OPAQUE = 'rgba(17,17,17, 1)';
const TRANSPARENT = 'rgba(17,17,17, .8)';

export const EVENTS = {
  EMIT: {
    CREATE_ROOM: 'CREATE_ROOM',
    JOIN_ROOM: 'JOIN_ROOM',
    SEND_MESSAGE: 'SEND_MESSAGE',
    MARK_AS_READ: 'MARK_AS_READ',
  },
  ON: {
    JOINED_ROOM: 'JOINED_ROOM',
    MESSAGES: 'MESSAGES',
    USER_ONLINE: 'USER_ONLINE',
    USER_OFFLINE: 'USER_OFFLINE',
    NEW_MESSAGE: 'NEW_MESSAGE',
    NEW_CHAT_CREATED: 'NEW_CHAT_CREATED',
    MESSAGES_READ: 'MESSAGES_READ',
  },
};

export const constants = { OPAQUE, TRANSPARENT };
