const OPAQUE = 'rgba(17,17,17, 1)';
const TRANSPARENT = 'rgba(17,17,17, .8)';

export const EVENTS = {
  EMIT: {
    CREATE_ROOM: 'CREATE_ROOM',
    JOIN_ROOM: 'JOIN_ROOM',
    SEND_MESSAGE: 'SEND_MESSAGE',
    MARK_AS_READ: 'MARK_AS_READ',
    REACT_TO_MESSAGE: 'REACT_TO_MESSAGE',
    UNREACT_TO_MESSAGE: 'UNREACT_TO_MESSAGE',
    TYPING: 'TYPING',
    STOP_TYPING: 'STOP_TYPING',
    EDIT_MESSAGE: 'EDIT_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
  },
  ON: {
    JOINED_ROOM: 'JOINED_ROOM',
    MESSAGES: 'MESSAGES',
    USER_ONLINE: 'USER_ONLINE',
    USER_OFFLINE: 'USER_OFFLINE',
    NEW_MESSAGE: 'NEW_MESSAGE',
    NEW_CHAT_CREATED: 'NEW_CHAT_CREATED',
    MESSAGES_READ: 'MESSAGES_READ',
    MESSAGE_REACTED: 'MESSAGE_REACTED',
    MESSAGE_UNREACTED: 'MESSAGE_UNREACTED',
    USER_TYPING: 'USER_TYPING',
    USER_STOPPED_TYPING: 'USER_STOPPED_TYPING',
    MESSAGE_EDITED: 'MESSAGE_EDITED',
    MESSAGE_DELETED: 'MESSAGE_DELETED',
  },
};

const DEFAULT_EMOJIS = ['👍', '❤️', '😂', '😮', '😢', '🙏'];

export const constants = { OPAQUE, TRANSPARENT, DEFAULT_EMOJIS };
